### PR TITLE
Feature/reset-password

### PR DESCRIPTION
**Pull request by LiamSingh64**
This PR:
- Adds a new RouterView specifically for users resetting their password containing an input field for user email and submit button
- A new function added to the Composables/example.js file that authenticates the user and sends an Email with a link to reset password
- New route to RouteView in router
- Router-Link to RouteView in LoginView (according to sitemap)
- TINY change to database.js for authentication

### CODE REVIEW

**Comment by LiamSingh64** [comment]
should I add a router-link that goes BACK to the login page?

**Comment by LiamSingh64** [comment]
Still need to add a proper modal (probs with Bootstrap) or is it not needed?

**Comment by rwx-yxu** [comment]
Actual error:      
```
FirebaseError: The following error originated from your application code, not from Cypress.
```
Might very well be an error from one of the other commands rather than cypress specifically.

**Comment by rwx-yxu** [comment]
I can run cypress tests on local machine but the action runner has an issue with the auth:
```
> Firebase: Error (auth/invalid-api-key).
```
Could be related to the line change for
```
const firebaseAuth = getAuth(app);
```

**Comment by rwx-yxu** [comment]
although the cypress test does "pass", the actual video output doesn't even show the home page. Compared to the other working braches.

**Comment by rwx-yxu** [comment]
Code just doesn't work. Need to rewrite way that reset link is being set.

* no idea why is example.js is being used when I explicitly said to leave that file as is.
* importing firebase individually rather than use firebase/database.js is just wrong. This is because it is importing new instances of those methods that are not configured with the app settings for vite.

**Comment by rwx-yxu** [comment]
Still failing... I'll review the secrets from firebase project.

**Pull request merged**
