### PR TITLE
Core/fire store setup

### PR DESCRIPTION
**Pull request by rwx-yxu**
This pull request should add support for firebase config. Upload hcm csv data script support added as well.

It is recommended for reviewers to test the pull request by running the script without the csv file, with the csv file on a new fire store host instance. And run once more to verify that nothing will be added once the data has been uploaded

### CODE REVIEW

**Comment by rwx-yxu** [comment]
Remembered that I need to add an additional column for created_by_user_id field on the hcm data

**Comment by rwx-yxu** [comment]
Probs the best way to go about this is to delete all the data currently in firestore for hcm and rerun.

**Review by D4ni3l8 — APPROVED** [review]

**Comment by LiamSingh64** [comment]
Had some trouble setting it up, but that was just me being an idiot:sweat_smile:. Apart from that, it all worked great, but would it be better to have the hcm_data.csv file INSIDE the Utils folder or no?

Side-note: Documents are organized alphabetically by Capital letters, and then Lower-Case letters, just saying that for anyone else because that confused me when looking for the "created_by_user_id" key:thumbsup:

**Comment by rwx-yxu** [comment]
Don't really see a reason to not upload the hcm csv I guess.

**Review by LiamSingh64 — APPROVED** [review]

**Pull request merged**
