### PR TITLE
Core/workflow testing

### PR DESCRIPTION
**Pull request by LiamSingh64**
This PR changed the import path for vite.config.js in the vitest.config.js file so that the commands `npm run test:unit` and `npm run test:e2e` work correctly and pass.

These commands should also be added to the Action Workflows which worked when ran locally. I suggest you switch to the 'core/workflow-testing' branch, and run these commands locally as well to make make sure they work/pass for you.

Please comment any issues/thoughts you find with these changes.

### CODE REVIEW

**Comment by rwx-yxu** [comment]
Eslint merge completed. Please can you double check if `npm run ci` will run linting for us. If not, then we will need to alter the workflow file to add `npm run lint`. Merging in main will be required for the eslint config setup first to test out.

**Comment by LiamSingh64** [comment]
Got this error when running lint from workflow:

Error: Process completed with exit code 1

**Comment by advweb-grp1** [comment]
Yeet the icon files.
Modify eslint config such that it now will exclude .vite.config.js and .cy* files because the tests are able to be ran just fine.

**Comment by LiamSingh64** [comment]
Ok so I deleted all the Icon .vue files but "src/components/TheWelcome.vue" imports all of them, and since we're not using this aswell, I just deleted it.

**Comment by LiamSingh64** [comment]
the flag --ignore-path for ESLint doesn't allow multiple paths so a workaround I found is to add an Environment comment which works totally fine!:thumbsup:

**Comment by rwx-yxu** [comment]
I am not entirely okay on the current implementation of App.Vue. All the layout has been defined in the HomeView.Vue file.

**Comment by advweb-grp1** [comment]
Build failed because the delete component was referenced in the home view.vue file. This shouldn't be handled in this pull request tbh because it dilutes what this pull request is doing when the original intention for this pull request is to `import path for vite.config.js in the vitest.config.js file so that the commands npm run test:unit and npm run test:e2e work correctly and pass.`
I will make one exception in this case because the original assignee did it. I am going to raise a separate clean up issue to handle stuff like removing the default files.

**Comment by rwx-yxu** [comment]
Resolving the linting import issues by adding some cypress config options to eslintrc.js file and disabling linting for `import { configDefaults } from 'vitest/config';` no idea why eslint isn't able to resolve this import but I can not seem to find a good solution online. Most sources point to adding this setting into the eslint.js file 
```
  settings: {
    'import/resolver': {
      alias: {
        map: [
          ['vitest/config', 'vitest/dist/config.js'],
        ],
        extensions: ['.js', '.vue'],
      },
    },
  },
```
But that doesn't work. I have verified that I can manually

**Review by rwx-yxu — APPROVED** [review]
Happy with the changes.

**Pull request merged**
