### PR TITLE
Core/scaffold

### PR DESCRIPTION
**Pull request by rwx-yxu**
This pull request should:
* Include vue project init
* Should have bootstrap enabled
* Empty views for each page.
* Must be tested by all members on their machines to ensure that this init is safe to merge.

### CODE REVIEW

**Review by advweb-grp1 — APPROVED** [review]
This is just a demo to the group on code reviews.

**Comment by advweb-grp1** [comment]
Works for me!

**Comment by rwx-yxu** [comment]
# Empty views for each page
Cannot be merged until this is done

**Review by AymanReh — APPROVED** [review]

**Comment by AymanReh** [comment]
works

**Review by LiamSingh64 — APPROVED** [review]
Works for me

**Comment by D4ni3l8** [comment]
works for me

**Review by D4ni3l8 — APPROVED** [review]

**Comment by rwx-yxu** [comment]
Closing pull request due to https://github.com/advweb-grp1/advanced-web-final-year-project/issues/5#issuecomment-1474834976

**Pull request closed without merging**
