### PR TITLE
core/layout

### PR DESCRIPTION
**Pull request by D4ni3l8**
This is the initial homepage layout.

### CODE REVIEW

**Comment by D4ni3l8** [comment]
The homepage is meant to look something like this
image

**Comment by rwx-yxu** [comment]
Reviewing current code implementation.

**Comment by rwx-yxu** [comment]
I am not entirely okay on the current implementation of App.Vue. All the layout has been defined in the HomeView.Vue file.

**Comment by rwx-yxu** [comment]
Reason why the views are not being routed is because the view file doesn't render routing views. The HomeView.Vue is a static file which hard codes that file so the buttons currently do nothing

**Comment by rwx-yxu** [comment]
Build fail log
```
error during build:
RollupError: Could not resolve "./views/Homeview.vue" from "src/App.vue"
    at error (file:///home/runner/work/advanced-web-final-year-project/advanced-web-final-year-project/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
    at ModuleLoader.handleInvalidResolvedId (file:///home/runner/work/advanced-web-final-year-project/advanced-web-final-year-project/node_modules/rollup/dist/es/shared/node-entry.js:[23](https://github.com/advweb-grp1/advanced-web-final-year-project/actions/runs/4566231636/jobs/8058440400?pr=24#step:3:24)777:[24](https://github.com/advweb-grp1/advanced-web-final-year-project/actions/runs/4566231636/jobs/8058440400?pr=24#step:3:25))
    at file:///home/runner/work/advanced-web-final-year-project/advanced-web-final-year-project/node_modules/rollup/dist/es/shared/node-entry.js:23739:[26](https://github.com/advweb-grp1/advanced-web-final-year-project/actions/runs/4566231636/jobs/8058440400?pr=24#step:3:27)
Error: Process completed with exit code 1.
```

**Comment by rwx-yxu** [comment]
I am gonna move the nav bar into app.Vue and use bootstrap to make the general layout along  whereby there will be a router-view in a main tag

**Comment by rwx-yxu** [comment]
Wont pass linting in its current state as well.

**Comment by rwx-yxu** [comment]
Removing the main.css that is being imported in main.js. The default css created by vue init was probs the source of some of the issues that Daniel was facing which pushed him to avoid App.vue.
Before:
image
After removing main.css
image

**Comment by rwx-yxu** [comment]
Need to do some clean up:
- Remove the bootstrap component entirely. That component was just a test to prove bootstrap integration. This is no longer needed anymore.
- Remove reset from the nav list since the site map shows that the reset is only accessible from the login and register pages.

**Comment by rwx-yxu** [comment]
Moving nav bar into its own component file. It's a chance to write up a vitest as well to test it out.

**Comment by rwx-yxu** [comment]
looking at the changes required, its safer to raise a separate pull request to add testing. Will definately be hitting conflics with #23 because I need to modify vitetest.config.js to remove the cardiomyopathy directory.

**Comment by rwx-yxu** [comment]
Still going to push up NavBar.vue.
Probs best to raise two separate pull requests. One for navbar testing and another for clean to remove the rest of the default welcome stuff. I would like to do it in this pull request but Liam already has removed some files like the icons already and went ahead to remove one of the welcome files. Best to keep the pull requests specific to their purpose rather than to pollute it with additional extras on top.

**Review by LiamSingh64 — APPROVED** [review]

**Review by rwx-yxu — APPROVED** [review]
Happy with the changes.

**Pull request merged**
