### PR TITLE
feature/addData

### PR DESCRIPTION
**Pull request by D4ni3l8**
This is the initial add data page. I will make a dropbox where the user is able to insert files and upload them to firebase.

### CODE REVIEW

**Comment by LiamSingh64** [comment]
added bootstrap so it looks better, input-types changed so they reflect data-types more appropriately, added html element to upload a file

**Comment by LiamSingh64** [comment]
Is the user only allowed to upload .csv data? If yes, I will change `<input type="file">` to `<input type="file" accept=".csv">`

**Comment by rwx-yxu** [comment]
> Is the user only allowed to upload .csv data? If yes, I will change `<input type="file">` to `<input type="file" accept=".csv">`

I would suggest to review the usecase for add data #8

**Comment by rwx-yxu** [comment]
current layout for reference:
image

**Comment by LiamSingh64** [comment]
User can now add data manually and add it to firestore, still need to create method to parse uploaded file!

**Comment by LiamSingh64** [comment]
Please lemme know if i'm missing anything from the hcm json data being added to firestore
Here's how it currently looks with example:
{
  ACTCmutation: 0
  AgeatMRI: 45,
  ApicalHCM: 1,
  Diabetes: 1,
  Hypertension: 1,
  MYBPC3mutation: 
  MYH7: 0,
  MYL2: 0,
  Myectomy: 0,
  SuddenCardiacDeath: 0,
  TNNCI: 0,
  TNNI3: 0,
  TNNT2mutation: 0,
  TPM1: 0,
  TT: 0,
  female: 0,
  ledv: 0,
  lesv: 2,
  lsv: 8,
  lvef: 4,
  lvmass: 6,
  redv: 1,
  resv: 3,
  rsv: 9,
  rvef: 5,
  rvmass: 7,
  scar: 0
}

**Comment by LiamSingh64** [comment]
TODO:

- [ ] Add timestamp to document
- [ ] Find User email and send confirmation
- [ ] Add modal after submission for success/failure
- [ ] Add file parsing method and auto-fill fields for user confirmation

**Comment by LiamSingh64** [comment]
Think I MIGHT have added loads of empty test documents to prod database! :dizzy_face:

Good thing we can just reset/reupload dataset right?😬

**Comment by LiamSingh64** [comment]
https://firebase.google.com/docs/extensions/official/firestore-send-email
We need to trigger an email to the user after a doc has been added to comply with the usecase, which this extension does exactly!

Looks like to use this however, we will need to setup our own SMTP server? I'll try to find an alternative but this looks like the prime method for sending user emails at the moment😢 
image

**Comment by LiamSingh64** [comment]
I will set up an account with SendGrid and download the TriggerEmail extension, to hopefully implement a triggered email on document uploads for HCM data...:crossed_fingers:

**Comment by LiamSingh64** [comment]
- Get rid of non-genes in mutations
- Split hr data into right/left (2 cols)
- Change Checkboxes into Radios so it fits on 1 line https://getbootstrap.com/docs/5.2/components/button-group/#checkbox-and-radio-button-groups
- Add user-id to document https://github.com/advweb-grp1/advanced-web-final-year-project/pull/35#issuecomment-1509956637

**Comment by LiamSingh64** [comment]
build failing due to NavBar.vue, have a fix ready!

**Comment by LiamSingh64** [comment]
- [ ] Commit Fix for failing build (NavBar.spec.js)
- [ ] Change 'Upload Patient Data File or Add Manually' to header 'Upload Patient Data' ABOVE `<input type='file'>`
- [ ] Add submit button below uploadFile
- [ ] Add 'Add Manually' header below submit button
- [ ] Make input field width equal to uploadFile width
- [ ] Make first checkbutton row equal column width (Bootstrap)
- [ ] Change addHcmData and parsePatientData so uploaded csv can have multiple rows that will be added to firestore collection

**Comment by LiamSingh64** [comment]
This PR:
- Creates AddView.vue so uses can either upload a .csv which is parsed to 'bulk' add patient data, or manually input and submit individual patient information. This is added to the FireStore collection and Pinia Store
- Adds ModalComponent.vue (with slots for Title and Body) which can be triggered programmatically using `document.getElementById('modalTrigger'.click();`
- adds addData to NavBarItems once user is logged in
- changes NavBar test to expect 4 items instead of 3

**Comment by LiamSingh64** [comment]
- [ ] put asterix
- [ ] captilize age
- [ ] default gender
- [ ] change to "submit data" and "add file"
- [ ] add small easy unit tests
- [ ] add extra fields from chat

**Comment by LiamSingh64** [comment]
## Converting JS Date to/from Excel 'Date'
```
function JSDateToExcelDate(inDate) {
  inDate = new Date(inDate);
  var returnDateTime = 25569.0 + ((inDate.getTime() - (inDate.getTimezoneOffset() * 60 * 1000)) / (1000 * 60 * 60 * 24));
  return returnDateTime;
}
```
```
  function ExcelDateToJSDate(serial) {
   var utc_days  = Math.floor(serial - 25569);
   var utc_value = utc_days * 86400;                                        
   var date_info = new Date(utc_value * 1000);

   var fractional_day = serial - Math.floor(serial) + 0.0000001;

   var total_seconds = Math.floor(86400 * fractional_day);

   var seconds = total_seconds % 60;

   total_seconds -= seconds;

   var hours = Math.floor(total_seconds / (60 * 60));
   var minutes = Math.floor(total_seconds / 60) % 60;

   return new Date(date_info.getFullYear(), date_info.getMonth(), date_info.getDate(), hours, minutes, seconds);
}
```

**Comment by rwx-yxu** [comment]
Bulk upload and manual upload works. Only change I would suggest is to clear the forms after a successful submission. There is also a question around if we should make it okay for 0 values but probs something that our tutor can answer tbh.

**Pull request merged**
