### PR TITLE
added eslint.js

### PR DESCRIPTION
**Pull request by AymanReh**
Fixed styling errors in src folder
Added eslintrc.js
Made sure it works alongside ESlint plugin.

### CODE REVIEW

**Comment by rwx-yxu** [comment]
Attaching reviewers

**Review by rwx-yxu — APPROVED** [review]
Happy with the changes. Verified that eslint plugin is now being enforced on local machine.

**Comment by rwx-yxu** [comment]
I actually noticed that the linting hasn't been added to the workflow. Refer to this comment https://github.com/advweb-grp1/advanced-web-final-year-project/issues/19#issuecomment-1478774709

**Comment by LiamSingh64** [comment]
Had to run `npm install eslint-plugin-import@latest --save-dev` for command `npm run lint` to work. Can this just be added to the package.json?

**Comment by advweb-grp1** [comment]
Already have eslint-plugin-import in package.json

**Comment by advweb-grp1** [comment]
Not sure if the linting is ran when the command `npm run ci` part. Need to research

**Comment by advweb-grp1** [comment]
Not sure if the linting is ran when the command `npm run ci` part. Need to research

**Review by advweb-grp1 — APPROVED** [review]

**Pull request merged**
